apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim1
  labels:
    app: mongodb
spec:
  storageClassName: slow
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
